# Generated by Django 5.0.6 on 2024-06-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='city',
            new_name='address',
        ),
    ]
